'[Topic] Enhancementâœ¨': ['feature/*','feat/*', 'feat(*)/*']
'[Topic] BugğŸ›': ['hotfix/*', 'fix/*', 'bugfix/*']
'[Topic] DocumentationğŸ“„': ['docs/*', 'doc/*']
'[Topic] DesignğŸ¨' : ['style/*', 'design/']
'[Topic] Refactorâ™»ï¸' : 'refactor/*'
'[Topic] Performance' : 'perf/*'
'[Topic] CIğŸ”§' : ['ci/*', 'build/*']
'[Topic] Testâ˜‘' : ['test/*', 'tests/*']
'[Topic] Otherâ”' : ['chore/*']