- color: "F4076B"
  description: "This is MUST do"
  name: "[Priority] High ğŸ’¨"
- color: "377514"
  description: "This is NEEDED, but do later"
  name: "[Priority] Middle ğŸ¨"
- color: "062CEF"
  description: "This SHOULD be exists, but can be after release"
  name: "[Priority] Low ğŸ’¤"
- color: "E2169D"
  description: "This PR is work in progress"
  name: "[Status] WIP ğŸš§"
- color: "97F87E"
  description: "This PR is done and need reviews"
  name: "[Status] Needs review ğŸ‘€"
- color: "B111CC"
  description: "Now working on this issue"
  name: "[Status] In progress ğŸ’"
- color: "008672"
  description: "Maybe someone can solve the problem"
  name: "[Status] Help wanted ğŸ¥º"
- color: "60F703"
  description: "I can't fix and help required"
  name: "[Status] Full stuck ğŸ˜µ"
- color: "FFFFFF"
  description: "This will not be worked on"
  name: "[Status] Give up ğŸ˜¥"
- color: "d73a4a"
  description: "Something isn't working"
  name: "[Topic] Bug ğŸ›"
- color: "0075ca"
  description: "Improvements or additions to documentation"
  name: "[Topic] Documentation ğŸ“„"
- color: "a2eeef"
  description: "New feature or improve feature"
  name: "[Topic] Enhancement âœ¨"
- color: "40E6B2"
  description: "Speed up process"
  name: "[Topic] Performance ğŸ’¨"
- color: "7057ff"
  description: "Refactor bad codes"
  name: "[Topic] Refactor ğŸ”¨"
- color: "EBE686"
  description: "Add test codes to features"
  name: "[Topic] Test âœ…"
- color: "783925"
  description: "Style or design change"
  name: "[Topic] Design ğŸ¨"
- color: "1F1B98"
  description: "Github actions or auto build things"
  name: "[Topic] CI ğŸ”§"
- color: "7DF93F"
  description: "Development environment things"
  name: "[Topic] DevOps ğŸ”§"
- color: "1C3F72"
  description: "Fix type hinting"
  name: "[Topic] Typing ğŸ§©"
- color: "e4e669"
  description: "This issue doesn't seem right"
  name: "[Topic] Invalid â“"
- color: "cfd3d7"
  description: "This issue or pull request already exists"
  name: "[Topic] Duplicate ğŸ˜©"
- color: "16FB48"
  description: "General issues that can't be categorized"
  name: "[Topic] Other â”"