name: "✒ Lint style files with stylelint using reviewdog"

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop
    paths:
      - '**/*.css'
      - '**/*.scss'

jobs:
  stylelint:
    name: "✒ lint css/scss"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.KIRARI_TOKEN }}
          reporter: github-pr-review
          stylelint_input:
            - '**/*.css'
            - '**/*.scss'